apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-notebook
  namespace: bob
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 501
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: tensorflow-notebook
      image: jupyter/tensorflow-notebook:tensorflow-2.4.3
      command:  
        - "sleep"
        - "infinity"
      workingDir: /
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - mountPath: /workspace/mydir
          name: bob-nfs
        - mountPath: /home/bob
          name: bob-home-dir
      env:
        - name: "HOME"
          value: /home/bob
  nodeSelector:
    resourcetype: gpu
  volumes:
    - name: bob-nfs
      persistentVolumeClaim:
        claimName: nfs-pvc-bob
    - name: bob-home-dir
      emptyDir: {}
