apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-notebook
  namespace: alice
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 502
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: tensorflow-notebook
      image: jupyter/tensorflow-notebook:tensorflow-2.4.3
      command:  
        - "sleep"
        - "infinity"
      workingDir: /
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - mountPath: /workspace/mydir
          name: alice-nfs
        - mountPath: /home/alice
          name: alice-home-dir
      env:
        - name: "HOME"
          value: /home/alice
  nodeSelector:
    resourcetype: gpu
  volumes:
    - name: alice-nfs
      persistentVolumeClaim:
        claimName: nfs-pvc-alice
    - name: alice-home-dir
      emptyDir: {}
