apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-alice
  namespace: alice
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /runai/alice
    server: 10.252.55.34