apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-bob
  namespace: bob
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /runai/bob
    server: 10.252.55.34