apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-bob
  namespace: bob
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi