apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-alice
  namespace: alice
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi